version: '3.8'

services:
  db:
    container_name: kioschool-database
    build:
      context: .
      dockerfile: ./DatabaseDockerfile
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kio-school-database
      PG_INITDB_ARGS: "--encoding=UTF8 --locale=ko_KR.UTF8 --lc-collate=ko_KR.UTF8 --lc-ctype=ko_KR.UTF8"
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: kioschool-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - kioschool_redis_data:/data
    environment:
      - REDIS_PASSWORD=mypassword

volumes:
  postgres_data:
  kioschool_redis_data: