spring:
  cloud:
    gcp:
      core:
        enabled: true
      trace:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    hikari:
      minimum-idle: 2 # 자주 발생하는 신규 커넥션 비용을 막기 위해 최소 2개는 풀에 대기시킴 (Warm Pool)
      idle-timeout: 60000 # 1분 대기 후 불필요한 추가 연결은 반환 처리
      max-lifetime: 540000 # 9분. 방화벽이나 오라클DB가 커넥션을 끊어버리기 전(보통 10분)에 먼저 깔끔하게 버림
      keepalive-time: 60000 # 1분 단위로 DB에 가볍게 핑을 찔러 죽은 커넥션 방지 (Cloud Run이 잠깐씩 깰 때마다 순환)
      connection-timeout: 1000 # (1초) 사용 가능한 커넥션이 없을 때 빠르게 Fail-Fast 처리 (대량 트래픽 시 병목 방지)
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
  thymeleaf:
    enabled: false
  mail:
    host: smtp.migadu.com
    port: 465
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
jwt:
  secret-key: "${JWT_SECRET_KEY}"
cloud:
  aws:
    s3:
      bucket: "${AWS_S3_BUCKET}"
    credentials:
      access-key: "${AWS_S3_ACCESS_KEY}"
      secret-key: "${AWS_S3_SECRET_KEY}"
    region:
      static: ap-northeast-2
    stack:
      auto: false
server:
  tomcat:
    threads:
      min-spare: 10
      max: 120
    accept-count: 100
    remoteip:
      internal-proxies: ".*"
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
  servlet:
    session:
      cookie:
        same-site: none
  error:
    include-message: always
  forward-headers-strategy: native
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
portone:
  api-key: "${PORTONE_API_KEY}"
  api-secret: "${PORTONE_API_SECRET}"
management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1 # 10% 샘플링
  health:
    defaults:
      enabled: false