spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: mypassword
  datasource:
    url: jdbc:postgresql://localhost:2345/kio-school-database
    username: myuser
    password: mypassword
jwt:
  secret-key: 512393ea8dee67633d7f1197c4938239f57c1a323a227e919977f0b478c5f5fd3a4dab07ba1a796297c5cd7c9519e6403ad2742e0c07024290aafa3d6f9f2424
cloud:
  aws:
    s3:
      default-path: local
websocket:
  allowed-origins: "http://localhost:3000"
discord:
  webhook-url: "${DISCORD_WEBHOOK_URL}"
kioschool:
  base-url: "http://localhost:3000"
  cookie:
    secure: false
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: "*"