# Use an official PostgreSQL image as the base
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=kio-school-database

# Expose the PostgreSQL port
EXPOSE 2345

