version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: kioschool-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - kioschool_redis_data:/data
    environment:
      - REDIS_PASSWORD=mypassword

volumes:
  kioschool_redis_data: